prompt PL/SQL Developer Export Tables for user DEVELOPER@XE_VB
prompt Created by programacion7 on jueves, 25 de abril de 2024
set feedback off
set define off

prompt Disabling triggers for LAB_TIPOS_PROFESIONALES...
alter table LAB_TIPOS_PROFESIONALES disable all triggers;
prompt Disabling triggers for LAB_PROFESIONALES...
alter table LAB_PROFESIONALES disable all triggers;
prompt Disabling triggers for LAB_TIPOS_PEDIDOS...
alter table LAB_TIPOS_PEDIDOS disable all triggers;
prompt Disabling triggers for LAB_ESTADOS_PEDIDOS...
alter table LAB_ESTADOS_PEDIDOS disable all triggers;
prompt Disabling triggers for LAB_PACIENTES...
alter table LAB_PACIENTES disable all triggers;
prompt Disabling triggers for LAB_PEDIDOS...
alter table LAB_PEDIDOS disable all triggers;
prompt Disabling triggers for LAB_GENEROS...
alter table LAB_GENEROS disable all triggers;
prompt Disabling triggers for LAB_VALORES_REFERENCIA...
alter table LAB_VALORES_REFERENCIA disable all triggers;
prompt Disabling triggers for LAB_DET_PEDIDOS...
alter table LAB_DET_PEDIDOS disable all triggers;
prompt Disabling triggers for LAB_IMPUESTOS...
alter table LAB_IMPUESTOS disable all triggers;
prompt Disabling triggers for LAB_TIPOS_ESTUDIOS...
alter table LAB_TIPOS_ESTUDIOS disable all triggers;
prompt Disabling triggers for LAB_ESTUDIOS...
alter table LAB_ESTUDIOS disable all triggers;
prompt Disabling triggers for LAB_ESTUDIOS_PRECIOS...
alter table LAB_ESTUDIOS_PRECIOS disable all triggers;
prompt Disabling triggers for LAB_ESTUDIOS_VALOR_REF...
alter table LAB_ESTUDIOS_VALOR_REF disable all triggers;
prompt Disabling triggers for LAB_TIPOS_PRECIOS...
alter table LAB_TIPOS_PRECIOS disable all triggers;
prompt Disabling triggers for PERMISOS...
alter table PERMISOS disable all triggers;
prompt Disabling triggers for PERMISOS_PAGINAS...
alter table PERMISOS_PAGINAS disable all triggers;
prompt Disabling triggers for ROLES...
alter table ROLES disable all triggers;
prompt Disabling triggers for ROLES_PERMISOS...
alter table ROLES_PERMISOS disable all triggers;
prompt Disabling triggers for USUARIOS...
alter table USUARIOS disable all triggers;
prompt Disabling triggers for ROLES_USUARIOS...
alter table ROLES_USUARIOS disable all triggers;
prompt Disabling triggers for RT_EMPRESAS...
alter table RT_EMPRESAS disable all triggers;
prompt Disabling triggers for RT_BANCOS...
alter table RT_BANCOS disable all triggers;
prompt Disabling triggers for RT_CARGOS...
alter table RT_CARGOS disable all triggers;
prompt Disabling triggers for RT_ESPECIALISTAS...
alter table RT_ESPECIALISTAS disable all triggers;
prompt Disabling triggers for RT_CARGOS_ESPECIALISTAS...
alter table RT_CARGOS_ESPECIALISTAS disable all triggers;
prompt Disabling triggers for RT_FORMAS_PAGO...
alter table RT_FORMAS_PAGO disable all triggers;
prompt Disabling triggers for RT_COBROS...
alter table RT_COBROS disable all triggers;
prompt Disabling triggers for RT_PACIENTES...
alter table RT_PACIENTES disable all triggers;
prompt Disabling triggers for RT_RESERVAS...
alter table RT_RESERVAS disable all triggers;
prompt Disabling triggers for RT_CONSULTAS...
alter table RT_CONSULTAS disable all triggers;
prompt Disabling triggers for RT_CONS_DATOS_PAC...
alter table RT_CONS_DATOS_PAC disable all triggers;
prompt Disabling triggers for RT_MONEDAS...
alter table RT_MONEDAS disable all triggers;
prompt Disabling triggers for RT_COTIZACIONES...
alter table RT_COTIZACIONES disable all triggers;
prompt Disabling triggers for RT_DOCUMENTOS...
alter table RT_DOCUMENTOS disable all triggers;
prompt Disabling triggers for RT_DOCUMENTOS_DET...
alter table RT_DOCUMENTOS_DET disable all triggers;
prompt Disabling triggers for RT_IMPUESTOS...
alter table RT_IMPUESTOS disable all triggers;
prompt Disabling triggers for RT_PARAMETROS_DOC...
alter table RT_PARAMETROS_DOC disable all triggers;
prompt Disabling triggers for RT_PARAMETROS_USUARIOS...
alter table RT_PARAMETROS_USUARIOS disable all triggers;
prompt Disabling triggers for RT_SERVICIOS...
alter table RT_SERVICIOS disable all triggers;
prompt Disabling triggers for RT_RESERVAS_SERVICIOS...
alter table RT_RESERVAS_SERVICIOS disable all triggers;
prompt Disabling triggers for RT_SERVICIOS_PRECIOS...
alter table RT_SERVICIOS_PRECIOS disable all triggers;
prompt Disabling triggers for RT_TIPOS_DOCUMENTOS...
alter table RT_TIPOS_DOCUMENTOS disable all triggers;
prompt Disabling triggers for RT_TURNOS_CAB...
alter table RT_TURNOS_CAB disable all triggers;
prompt Disabling triggers for RT_TURNOS_DET...
alter table RT_TURNOS_DET disable all triggers;
prompt Disabling triggers for USUARIOS_EMPRESAS...
alter table USUARIOS_EMPRESAS disable all triggers;
prompt Deleting USUARIOS_EMPRESAS...
delete from USUARIOS_EMPRESAS;
prompt Deleting RT_TURNOS_DET...
delete from RT_TURNOS_DET;
prompt Deleting RT_TURNOS_CAB...
delete from RT_TURNOS_CAB;
prompt Deleting RT_TIPOS_DOCUMENTOS...
delete from RT_TIPOS_DOCUMENTOS;
prompt Deleting RT_SERVICIOS_PRECIOS...
delete from RT_SERVICIOS_PRECIOS;
prompt Deleting RT_RESERVAS_SERVICIOS...
delete from RT_RESERVAS_SERVICIOS;
prompt Deleting RT_SERVICIOS...
delete from RT_SERVICIOS;
prompt Deleting RT_PARAMETROS_USUARIOS...
delete from RT_PARAMETROS_USUARIOS;
prompt Deleting RT_PARAMETROS_DOC...
delete from RT_PARAMETROS_DOC;
prompt Deleting RT_IMPUESTOS...
delete from RT_IMPUESTOS;
prompt Deleting RT_DOCUMENTOS_DET...
delete from RT_DOCUMENTOS_DET;
prompt Deleting RT_DOCUMENTOS...
delete from RT_DOCUMENTOS;
prompt Deleting RT_COTIZACIONES...
delete from RT_COTIZACIONES;
prompt Deleting RT_MONEDAS...
delete from RT_MONEDAS;
prompt Deleting RT_CONS_DATOS_PAC...
delete from RT_CONS_DATOS_PAC;
prompt Deleting RT_CONSULTAS...
delete from RT_CONSULTAS;
prompt Deleting RT_RESERVAS...
delete from RT_RESERVAS;
prompt Deleting RT_PACIENTES...
delete from RT_PACIENTES;
prompt Deleting RT_COBROS...
delete from RT_COBROS;
prompt Deleting RT_FORMAS_PAGO...
delete from RT_FORMAS_PAGO;
prompt Deleting RT_CARGOS_ESPECIALISTAS...
delete from RT_CARGOS_ESPECIALISTAS;
prompt Deleting RT_ESPECIALISTAS...
delete from RT_ESPECIALISTAS;
prompt Deleting RT_CARGOS...
delete from RT_CARGOS;
prompt Deleting RT_BANCOS...
delete from RT_BANCOS;
prompt Deleting RT_EMPRESAS...
delete from RT_EMPRESAS;
prompt Deleting ROLES_USUARIOS...
delete from ROLES_USUARIOS;
prompt Deleting USUARIOS...
delete from USUARIOS;
prompt Deleting ROLES_PERMISOS...
delete from ROLES_PERMISOS;
prompt Deleting ROLES...
delete from ROLES;
prompt Deleting PERMISOS_PAGINAS...
delete from PERMISOS_PAGINAS;
prompt Deleting PERMISOS...
delete from PERMISOS;
prompt Deleting LAB_TIPOS_PRECIOS...
delete from LAB_TIPOS_PRECIOS;
prompt Deleting LAB_ESTUDIOS_VALOR_REF...
delete from LAB_ESTUDIOS_VALOR_REF;
prompt Deleting LAB_ESTUDIOS_PRECIOS...
delete from LAB_ESTUDIOS_PRECIOS;
prompt Deleting LAB_ESTUDIOS...
delete from LAB_ESTUDIOS;
prompt Deleting LAB_TIPOS_ESTUDIOS...
delete from LAB_TIPOS_ESTUDIOS;
prompt Deleting LAB_IMPUESTOS...
delete from LAB_IMPUESTOS;
prompt Deleting LAB_DET_PEDIDOS...
delete from LAB_DET_PEDIDOS;
prompt Deleting LAB_VALORES_REFERENCIA...
delete from LAB_VALORES_REFERENCIA;
prompt Deleting LAB_GENEROS...
delete from LAB_GENEROS;
prompt Deleting LAB_PEDIDOS...
delete from LAB_PEDIDOS;
prompt Deleting LAB_PACIENTES...
delete from LAB_PACIENTES;
prompt Deleting LAB_ESTADOS_PEDIDOS...
delete from LAB_ESTADOS_PEDIDOS;
prompt Deleting LAB_TIPOS_PEDIDOS...
delete from LAB_TIPOS_PEDIDOS;
prompt Deleting LAB_PROFESIONALES...
delete from LAB_PROFESIONALES;
prompt Deleting LAB_TIPOS_PROFESIONALES...
delete from LAB_TIPOS_PROFESIONALES;
prompt Loading LAB_TIPOS_PROFESIONALES...
prompt Table is empty
prompt Loading LAB_PROFESIONALES...
prompt Table is empty
prompt Loading LAB_TIPOS_PEDIDOS...
prompt Table is empty
prompt Loading LAB_ESTADOS_PEDIDOS...
prompt Table is empty
prompt Loading LAB_PACIENTES...
prompt Table is empty
prompt Loading LAB_PEDIDOS...
prompt Table is empty
prompt Loading LAB_GENEROS...
prompt Table is empty
prompt Loading LAB_VALORES_REFERENCIA...
prompt Table is empty
prompt Loading LAB_DET_PEDIDOS...
prompt Table is empty
prompt Loading LAB_IMPUESTOS...
prompt Table is empty
prompt Loading LAB_TIPOS_ESTUDIOS...
prompt Table is empty
prompt Loading LAB_ESTUDIOS...
prompt Table is empty
prompt Loading LAB_ESTUDIOS_PRECIOS...
prompt Table is empty
prompt Loading LAB_ESTUDIOS_VALOR_REF...
prompt Table is empty
prompt Loading LAB_TIPOS_PRECIOS...
prompt Table is empty
prompt Loading PERMISOS...
insert into PERMISOS (id, descripcion, explicacion, codigo, app_apex_id, ind_menu, page_apex_redirige)
values (4, 'CLIENTES', 'Edición general de clientes', 1, 100, 'S', 1);
prompt 1 records loaded
prompt Loading PERMISOS_PAGINAS...
insert into PERMISOS_PAGINAS (id, permiso_id, app_id, page_id, ind_menu_principal, fecha_grab)
values (29, 4, 100, 2, 'N', to_date('22-01-2024 21:19:18', 'dd-mm-yyyy hh24:mi:ss'));
insert into PERMISOS_PAGINAS (id, permiso_id, app_id, page_id, ind_menu_principal, fecha_grab)
values (30, 4, 100, 3, 'S', to_date('22-01-2024 21:19:36', 'dd-mm-yyyy hh24:mi:ss'));
prompt 2 records loaded
prompt Loading ROLES...
insert into ROLES (id, descripcion, explicacion, permiso_ids, empresa_id)
values (1, 'ADMINISTRADOR ODONTOLOGICO', 'ACCESO TOTAL', '4', 1);
prompt 1 records loaded
prompt Loading ROLES_PERMISOS...
insert into ROLES_PERMISOS (id, rol_id, permiso_id)
values (10, 1, 4);
prompt 1 records loaded
prompt Loading USUARIOS...
insert into USUARIOS (id, nombre, apellido, login, pass, codigo, activo, rol_ids, empresa_ids)
values (3, 'PABLO', 'CESPEDES', 'PABLOC', '70EA6F7E3CBD7C8ABA2C9D7C0A05DD0E', 1, 'S', null, null);
prompt 1 records loaded
prompt Loading ROLES_USUARIOS...
prompt Table is empty
prompt Loading RT_EMPRESAS...
insert into RT_EMPRESAS (id, razon_social, explotacion, ruc, dir, tel, mail, lat, lng, creado, creado_por, modificado, modificado_por)
values (2, 'BARBER SHOP', 'Barbería', '2222222-1', 'Hohenau, Colonias Unidas frente mismo a la Cooperativa Universitaria', '0988666777', 'barber@sample.com.py', '0', '0', to_date('13-01-2024 16:28:17', 'dd-mm-yyyy hh24:mi:ss'), 'ADMIN', to_date('13-01-2024 16:28:17', 'dd-mm-yyyy hh24:mi:ss'), 'ADMIN');
insert into RT_EMPRESAS (id, razon_social, explotacion, ruc, dir, tel, mail, lat, lng, creado, creado_por, modificado, modificado_por)
values (1, 'ODONTOLOGIA DIGITAL', 'Odontología Familiar', '1111111-1', 'Juan Eulogio Estigarribia, sobre Ruta Internacional Nº 2. a metros del Centro de Salud', '0985222333', 'odontologia@sample.com.py', '0', '0', to_date('13-01-2024 15:59:10', 'dd-mm-yyyy hh24:mi:ss'), 'ADMIN', to_date('13-01-2024 15:59:10', 'dd-mm-yyyy hh24:mi:ss'), 'ADMIN');
prompt 2 records loaded
prompt Loading RT_BANCOS...
prompt Table is empty
prompt Loading RT_CARGOS...
prompt Table is empty
prompt Loading RT_ESPECIALISTAS...
prompt Table is empty
prompt Loading RT_CARGOS_ESPECIALISTAS...
prompt Table is empty
prompt Loading RT_FORMAS_PAGO...
prompt Table is empty
prompt Loading RT_COBROS...
prompt Table is empty
prompt Loading RT_PACIENTES...
prompt Table is empty
prompt Loading RT_RESERVAS...
prompt Table is empty
prompt Loading RT_CONSULTAS...
prompt Table is empty
prompt Loading RT_CONS_DATOS_PAC...
prompt Table is empty
prompt Loading RT_MONEDAS...
prompt Table is empty
prompt Loading RT_COTIZACIONES...
prompt Table is empty
prompt Loading RT_DOCUMENTOS...
prompt Table is empty
prompt Loading RT_DOCUMENTOS_DET...
prompt Table is empty
prompt Loading RT_IMPUESTOS...
prompt Table is empty
prompt Loading RT_PARAMETROS_DOC...
prompt Table is empty
prompt Loading RT_PARAMETROS_USUARIOS...
prompt Table is empty
prompt Loading RT_SERVICIOS...
prompt Table is empty
prompt Loading RT_RESERVAS_SERVICIOS...
prompt Table is empty
prompt Loading RT_SERVICIOS_PRECIOS...
prompt Table is empty
prompt Loading RT_TIPOS_DOCUMENTOS...
prompt Table is empty
prompt Loading RT_TURNOS_CAB...
prompt Table is empty
prompt Loading RT_TURNOS_DET...
prompt Table is empty
prompt Loading USUARIOS_EMPRESAS...
prompt Table is empty
prompt Enabling triggers for LAB_TIPOS_PROFESIONALES...
alter table LAB_TIPOS_PROFESIONALES enable all triggers;
prompt Enabling triggers for LAB_PROFESIONALES...
alter table LAB_PROFESIONALES enable all triggers;
prompt Enabling triggers for LAB_TIPOS_PEDIDOS...
alter table LAB_TIPOS_PEDIDOS enable all triggers;
prompt Enabling triggers for LAB_ESTADOS_PEDIDOS...
alter table LAB_ESTADOS_PEDIDOS enable all triggers;
prompt Enabling triggers for LAB_PACIENTES...
alter table LAB_PACIENTES enable all triggers;
prompt Enabling triggers for LAB_PEDIDOS...
alter table LAB_PEDIDOS enable all triggers;
prompt Enabling triggers for LAB_GENEROS...
alter table LAB_GENEROS enable all triggers;
prompt Enabling triggers for LAB_VALORES_REFERENCIA...
alter table LAB_VALORES_REFERENCIA enable all triggers;
prompt Enabling triggers for LAB_DET_PEDIDOS...
alter table LAB_DET_PEDIDOS enable all triggers;
prompt Enabling triggers for LAB_IMPUESTOS...
alter table LAB_IMPUESTOS enable all triggers;
prompt Enabling triggers for LAB_TIPOS_ESTUDIOS...
alter table LAB_TIPOS_ESTUDIOS enable all triggers;
prompt Enabling triggers for LAB_ESTUDIOS...
alter table LAB_ESTUDIOS enable all triggers;
prompt Enabling triggers for LAB_ESTUDIOS_PRECIOS...
alter table LAB_ESTUDIOS_PRECIOS enable all triggers;
prompt Enabling triggers for LAB_ESTUDIOS_VALOR_REF...
alter table LAB_ESTUDIOS_VALOR_REF enable all triggers;
prompt Enabling triggers for LAB_TIPOS_PRECIOS...
alter table LAB_TIPOS_PRECIOS enable all triggers;
prompt Enabling triggers for PERMISOS...
alter table PERMISOS enable all triggers;
prompt Enabling triggers for PERMISOS_PAGINAS...
alter table PERMISOS_PAGINAS enable all triggers;
prompt Enabling triggers for ROLES...
alter table ROLES enable all triggers;
prompt Enabling triggers for ROLES_PERMISOS...
alter table ROLES_PERMISOS enable all triggers;
prompt Enabling triggers for USUARIOS...
alter table USUARIOS enable all triggers;
prompt Enabling triggers for ROLES_USUARIOS...
alter table ROLES_USUARIOS enable all triggers;
prompt Enabling triggers for RT_EMPRESAS...
alter table RT_EMPRESAS enable all triggers;
prompt Enabling triggers for RT_BANCOS...
alter table RT_BANCOS enable all triggers;
prompt Enabling triggers for RT_CARGOS...
alter table RT_CARGOS enable all triggers;
prompt Enabling triggers for RT_ESPECIALISTAS...
alter table RT_ESPECIALISTAS enable all triggers;
prompt Enabling triggers for RT_CARGOS_ESPECIALISTAS...
alter table RT_CARGOS_ESPECIALISTAS enable all triggers;
prompt Enabling triggers for RT_FORMAS_PAGO...
alter table RT_FORMAS_PAGO enable all triggers;
prompt Enabling triggers for RT_COBROS...
alter table RT_COBROS enable all triggers;
prompt Enabling triggers for RT_PACIENTES...
alter table RT_PACIENTES enable all triggers;
prompt Enabling triggers for RT_RESERVAS...
alter table RT_RESERVAS enable all triggers;
prompt Enabling triggers for RT_CONSULTAS...
alter table RT_CONSULTAS enable all triggers;
prompt Enabling triggers for RT_CONS_DATOS_PAC...
alter table RT_CONS_DATOS_PAC enable all triggers;
prompt Enabling triggers for RT_MONEDAS...
alter table RT_MONEDAS enable all triggers;
prompt Enabling triggers for RT_COTIZACIONES...
alter table RT_COTIZACIONES enable all triggers;
prompt Enabling triggers for RT_DOCUMENTOS...
alter table RT_DOCUMENTOS enable all triggers;
prompt Enabling triggers for RT_DOCUMENTOS_DET...
alter table RT_DOCUMENTOS_DET enable all triggers;
prompt Enabling triggers for RT_IMPUESTOS...
alter table RT_IMPUESTOS enable all triggers;
prompt Enabling triggers for RT_PARAMETROS_DOC...
alter table RT_PARAMETROS_DOC enable all triggers;
prompt Enabling triggers for RT_PARAMETROS_USUARIOS...
alter table RT_PARAMETROS_USUARIOS enable all triggers;
prompt Enabling triggers for RT_SERVICIOS...
alter table RT_SERVICIOS enable all triggers;
prompt Enabling triggers for RT_RESERVAS_SERVICIOS...
alter table RT_RESERVAS_SERVICIOS enable all triggers;
prompt Enabling triggers for RT_SERVICIOS_PRECIOS...
alter table RT_SERVICIOS_PRECIOS enable all triggers;
prompt Enabling triggers for RT_TIPOS_DOCUMENTOS...
alter table RT_TIPOS_DOCUMENTOS enable all triggers;
prompt Enabling triggers for RT_TURNOS_CAB...
alter table RT_TURNOS_CAB enable all triggers;
prompt Enabling triggers for RT_TURNOS_DET...
alter table RT_TURNOS_DET enable all triggers;
prompt Enabling triggers for USUARIOS_EMPRESAS...
alter table USUARIOS_EMPRESAS enable all triggers;

set feedback on
set define on
prompt Done
